num1 = int(input("Enter first number: "))
num2 = int(input("Enter another number: "))
print(f"Addition: {num1 + num2}")
print(f"Subtraction: {num1 - num2}")
print(f"Multiplication: {num1 * num2}")
print(f"Division: {round((num1 / num2), 2)}")
